# Attach this docker-compose file to disable HTTP server for MCP container, and use only STDIO protocol
# docker-compose  -f ./docker-compose.yml -f ./docker-compose.prod.yml -f .docker-compose.mcp-stdio-only.yml up -d
services:
  mcp:
    environment:
      - MCP_HTTP_ENABLED=false
    command: ["echo", "Using MCP server with STDIO transport only, from backend service..."]
    healthcheck:
      test: [ "CMD", "echo", "Using MCP server with STDIO transport only, from backend service..." ]
